# Generated by Django 3.1.3 on 2023-08-13 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_auto_20230813_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='total_enrollment',
            new_name='grade',
        ),
    ]
